name: Twittercard CI/CD

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: GCR Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: genesis331
          password: ${{ secrets.GCR_TOKEN }}
      -
        name: Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/genesis331/twittercard
